# Generated by Django 4.0.2 on 2022-02-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='внешний id')),
                ('instanceId', models.CharField(blank=True, max_length=255, null=True, verbose_name='instanceId')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Токен')),
                ('chat_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='id чата')),
                ('md', models.PositiveIntegerField(blank=True, null=True, verbose_name='md')),
                ('chat_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='chat_token')),
                ('chat_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='chat_key')),
                ('apikey', models.CharField(blank=True, max_length=255, null=True, verbose_name='apikey')),
                ('date_add', models.CharField(blank=True, max_length=255, null=True, verbose_name='date_add')),
                ('date_trial', models.CharField(blank=True, max_length=255, null=True, verbose_name='date_trial')),
                ('date_pay', models.CharField(blank=True, max_length=255, null=True, verbose_name='date_pay')),
                ('date_subscription', models.CharField(blank=True, max_length=255, null=True, verbose_name='date_subscription')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('platform', models.CharField(blank=True, max_length=255, null=True, verbose_name='platform')),
                ('status', models.PositiveIntegerField(blank=True, null=True, verbose_name='status')),
                ('is_premium', models.PositiveIntegerField(blank=True, null=True, verbose_name='is_premium')),
            ],
            options={
                'verbose_name': 'Информация о чате',
                'verbose_name_plural': 'Информация о чатах',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер телефона')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Информация о контакте',
                'verbose_name_plural': 'Информация о контактах',
            },
        ),
    ]
